# Generated by Django 4.1.3 on 2022-12-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VinylsBooksVideoGames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='title',
        ),
    ]
